// Mocks generated by Mockito 5.4.6 from annotations
// in fittrack/test/screens/weeks_screen_workout_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i10;

import 'package:fittrack/models/analytics.dart' as _i9;
import 'package:fittrack/models/exercise.dart' as _i6;
import 'package:fittrack/models/exercise_set.dart' as _i7;
import 'package:fittrack/models/program.dart' as _i3;
import 'package:fittrack/models/week.dart' as _i4;
import 'package:fittrack/models/workout.dart' as _i5;
import 'package:fittrack/providers/program_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProgramProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramProvider extends _i1.Mock implements _i2.ProgramProvider {
  MockProgramProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Program> get programs => (super.noSuchMethod(
        Invocation.getter(#programs),
        returnValue: <_i3.Program>[],
      ) as List<_i3.Program>);

  @override
  bool get isLoadingPrograms => (super.noSuchMethod(
        Invocation.getter(#isLoadingPrograms),
        returnValue: false,
      ) as bool);

  @override
  List<_i4.Week> get weeks => (super.noSuchMethod(
        Invocation.getter(#weeks),
        returnValue: <_i4.Week>[],
      ) as List<_i4.Week>);

  @override
  bool get isLoadingWeeks => (super.noSuchMethod(
        Invocation.getter(#isLoadingWeeks),
        returnValue: false,
      ) as bool);

  @override
  List<_i5.Workout> get workouts => (super.noSuchMethod(
        Invocation.getter(#workouts),
        returnValue: <_i5.Workout>[],
      ) as List<_i5.Workout>);

  @override
  bool get isLoadingWorkouts => (super.noSuchMethod(
        Invocation.getter(#isLoadingWorkouts),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.Exercise> get exercises => (super.noSuchMethod(
        Invocation.getter(#exercises),
        returnValue: <_i6.Exercise>[],
      ) as List<_i6.Exercise>);

  @override
  bool get isLoadingExercises => (super.noSuchMethod(
        Invocation.getter(#isLoadingExercises),
        returnValue: false,
      ) as bool);

  @override
  List<_i7.ExerciseSet> get sets => (super.noSuchMethod(
        Invocation.getter(#sets),
        returnValue: <_i7.ExerciseSet>[],
      ) as List<_i7.ExerciseSet>);

  @override
  bool get isLoadingSets => (super.noSuchMethod(
        Invocation.getter(#isLoadingSets),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingAnalytics => (super.noSuchMethod(
        Invocation.getter(#isLoadingAnalytics),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i7.ExerciseSet> getCurrentSets() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSets,
          [],
        ),
        returnValue: <_i7.ExerciseSet>[],
      ) as List<_i7.ExerciseSet>);

  @override
  void loadPrograms() => super.noSuchMethod(
        Invocation.method(
          #loadPrograms,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<String?> createProgram({
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProgram,
          [],
          {
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> updateProgram(_i3.Program? program) => (super.noSuchMethod(
        Invocation.method(
          #updateProgram,
          [program],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateProgramFields(
    String? programId, {
    String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgramFields,
          [programId],
          {
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> archiveProgram(String? programId) => (super.noSuchMethod(
        Invocation.method(
          #archiveProgram,
          [programId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> deleteProgram(String? programId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProgram,
          [programId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void selectProgram(_i3.Program? program) => super.noSuchMethod(
        Invocation.method(
          #selectProgram,
          [program],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadWeeks(String? programId) => super.noSuchMethod(
        Invocation.method(
          #loadWeeks,
          [programId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<String?> createWeek({
    required String? programId,
    required String? name,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWeek,
          [],
          {
            #programId: programId,
            #name: name,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> updateWeek(_i4.Week? week) => (super.noSuchMethod(
        Invocation.method(
          #updateWeek,
          [week],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateWeekFields(
    String? weekId, {
    String? name,
    String? notes,
    int? order,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWeekFields,
          [weekId],
          {
            #name: name,
            #notes: notes,
            #order: order,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> deleteWeek(
    String? programId,
    String? weekId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWeek,
          [
            programId,
            weekId,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> deleteWeekById(String? weekId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWeekById,
          [weekId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> duplicateWeek({
    required String? programId,
    required String? weekId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateWeek,
          [],
          {
            #programId: programId,
            #weekId: weekId,
          },
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);

  @override
  void selectWeek(_i4.Week? week) => super.noSuchMethod(
        Invocation.method(
          #selectWeek,
          [week],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadWorkouts(
    String? programId,
    String? weekId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #loadWorkouts,
          [
            programId,
            weekId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<String?> createWorkout({
    required String? programId,
    required String? weekId,
    required String? name,
    int? dayOfWeek,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkout,
          [],
          {
            #programId: programId,
            #weekId: weekId,
            #name: name,
            #dayOfWeek: dayOfWeek,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> updateWorkout(_i5.Workout? workout) => (super.noSuchMethod(
        Invocation.method(
          #updateWorkout,
          [workout],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteWorkout(
    String? programId,
    String? weekId,
    String? workoutId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkout,
          [
            programId,
            weekId,
            workoutId,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateWorkoutFields(
    String? workoutId, {
    String? name,
    int? dayOfWeek,
    String? notes,
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutFields,
          [workoutId],
          {
            #name: name,
            #dayOfWeek: dayOfWeek,
            #notes: notes,
            #orderIndex: orderIndex,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteWorkoutById(String? workoutId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkoutById,
          [workoutId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void selectWorkout(_i5.Workout? workout) => super.noSuchMethod(
        Invocation.method(
          #selectWorkout,
          [workout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadExercises(
    String? programId,
    String? weekId,
    String? workoutId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #loadExercises,
          [
            programId,
            weekId,
            workoutId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<String?> createExercise({
    required String? programId,
    required String? weekId,
    required String? workoutId,
    required String? name,
    required _i6.ExerciseType? exerciseType,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [],
          {
            #programId: programId,
            #weekId: weekId,
            #workoutId: workoutId,
            #name: name,
            #exerciseType: exerciseType,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> updateExercise(_i6.Exercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [exercise],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteExercise(
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            programId,
            weekId,
            workoutId,
            exerciseId,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateExerciseFields(
    String? exerciseId, {
    String? name,
    _i6.ExerciseType? exerciseType,
    String? notes,
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExerciseFields,
          [exerciseId],
          {
            #name: name,
            #exerciseType: exerciseType,
            #notes: notes,
            #orderIndex: orderIndex,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteExerciseById(String? exerciseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExerciseById,
          [exerciseId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void selectExercise(_i6.Exercise? exercise) => super.noSuchMethod(
        Invocation.method(
          #selectExercise,
          [exercise],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void loadSets(
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #loadSets,
          [
            programId,
            weekId,
            workoutId,
            exerciseId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<String?> createSet({
    required String? programId,
    required String? weekId,
    required String? workoutId,
    required String? exerciseId,
    int? reps,
    double? weight,
    int? duration,
    double? distance,
    int? restTime,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSet,
          [],
          {
            #programId: programId,
            #weekId: weekId,
            #workoutId: workoutId,
            #exerciseId: exerciseId,
            #reps: reps,
            #weight: weight,
            #duration: duration,
            #distance: distance,
            #restTime: restTime,
            #notes: notes,
          },
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> updateSet(_i7.ExerciseSet? set) => (super.noSuchMethod(
        Invocation.method(
          #updateSet,
          [set],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteSet(
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
    String? setId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSet,
          [
            programId,
            weekId,
            workoutId,
            exerciseId,
            setId,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> loadAnalytics({_i9.DateRange? dateRange}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAnalytics,
          [],
          {#dateRange: dateRange},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i9.PersonalRecord?> checkForPersonalRecord(
    _i7.ExerciseSet? set,
    _i6.Exercise? exercise,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForPersonalRecord,
          [
            set,
            exercise,
          ],
        ),
        returnValue: _i8.Future<_i9.PersonalRecord?>.value(),
      ) as _i8.Future<_i9.PersonalRecord?>);

  @override
  _i8.Future<void> refreshAnalytics() => (super.noSuchMethod(
        Invocation.method(
          #refreshAnalytics,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelections() => super.noSuchMethod(
        Invocation.method(
          #clearSelections,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
