// Mocks generated by Mockito 5.4.6 from annotations
// in fittrack/test/integration/program_provider_workout_exercise_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fittrack/models/analytics.dart' as _i2;
import 'package:fittrack/models/exercise.dart' as _i9;
import 'package:fittrack/models/exercise_set.dart' as _i10;
import 'package:fittrack/models/program.dart' as _i5;
import 'package:fittrack/models/week.dart' as _i7;
import 'package:fittrack/models/workout.dart' as _i8;
import 'package:fittrack/services/analytics_service.dart' as _i11;
import 'package:fittrack/services/firestore_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutAnalytics_0 extends _i1.SmartFake
    implements _i2.WorkoutAnalytics {
  _FakeWorkoutAnalytics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityHeatmapData_1 extends _i1.SmartFake
    implements _i2.ActivityHeatmapData {
  _FakeActivityHeatmapData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<Map<String, dynamic>?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>?>.empty(),
      ) as _i4.Stream<Map<String, dynamic>?>);

  @override
  _i4.Future<void> createUserProfile({
    required String? userId,
    String? displayName,
    String? email,
    Map<String, dynamic>? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserProfile,
          [],
          {
            #userId: userId,
            #displayName: displayName,
            #email: email,
            #settings: settings,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserProfile({
    required String? userId,
    String? displayName,
    String? email,
    Map<String, dynamic>? settings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #userId: userId,
            #displayName: displayName,
            #email: email,
            #settings: settings,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLastLogin(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #updateLastLogin,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i5.Program>> getPrograms(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrograms,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i5.Program>>.empty(),
      ) as _i4.Stream<List<_i5.Program>>);

  @override
  _i4.Stream<_i5.Program?> getProgram(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgram,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i4.Stream<_i5.Program?>.empty(),
      ) as _i4.Stream<_i5.Program?>);

  @override
  _i4.Future<String> createProgram(_i5.Program? program) => (super.noSuchMethod(
        Invocation.method(
          #createProgram,
          [program],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createProgram,
            [program],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateProgram(_i5.Program? program) => (super.noSuchMethod(
        Invocation.method(
          #updateProgram,
          [program],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProgramFields({
    required String? userId,
    required String? programId,
    String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgramFields,
          [],
          {
            #userId: userId,
            #programId: programId,
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> archiveProgram(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveProgram,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProgram(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProgram,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProgramCascade(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProgramCascade,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i7.Week>> getWeeks(
    String? userId,
    String? programId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeeks,
          [
            userId,
            programId,
          ],
        ),
        returnValue: _i4.Stream<List<_i7.Week>>.empty(),
      ) as _i4.Stream<List<_i7.Week>>);

  @override
  _i4.Stream<_i7.Week?> getWeek(
    String? userId,
    String? programId,
    String? weekId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeek,
          [
            userId,
            programId,
            weekId,
          ],
        ),
        returnValue: _i4.Stream<_i7.Week?>.empty(),
      ) as _i4.Stream<_i7.Week?>);

  @override
  _i4.Future<String> createWeek(_i7.Week? week) => (super.noSuchMethod(
        Invocation.method(
          #createWeek,
          [week],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createWeek,
            [week],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateWeek(_i7.Week? week) => (super.noSuchMethod(
        Invocation.method(
          #updateWeek,
          [week],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateWeekFields({
    required String? userId,
    required String? programId,
    required String? weekId,
    String? name,
    String? notes,
    int? order,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWeekFields,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekId: weekId,
            #name: name,
            #notes: notes,
            #order: order,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteWeek(
    String? userId,
    String? programId,
    String? weekId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWeek,
          [
            userId,
            programId,
            weekId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> duplicateWeek({
    required String? userId,
    required String? programId,
    required String? weekId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateWeek,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekId: weekId,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Stream<List<_i8.Workout>> getWorkouts(
    String? userId,
    String? programId,
    String? weekId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkouts,
          [
            userId,
            programId,
            weekId,
          ],
        ),
        returnValue: _i4.Stream<List<_i8.Workout>>.empty(),
      ) as _i4.Stream<List<_i8.Workout>>);

  @override
  _i4.Stream<_i8.Workout?> getWorkout(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkout,
          [
            userId,
            programId,
            weekId,
            workoutId,
          ],
        ),
        returnValue: _i4.Stream<_i8.Workout?>.empty(),
      ) as _i4.Stream<_i8.Workout?>);

  @override
  _i4.Future<String> createWorkout(_i8.Workout? workout) => (super.noSuchMethod(
        Invocation.method(
          #createWorkout,
          [workout],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createWorkout,
            [workout],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateWorkout(_i8.Workout? workout) => (super.noSuchMethod(
        Invocation.method(
          #updateWorkout,
          [workout],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateWorkoutFields({
    required String? userId,
    required String? programId,
    required String? weekId,
    required String? workoutId,
    String? name,
    int? dayOfWeek,
    String? notes,
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkoutFields,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekId: weekId,
            #workoutId: workoutId,
            #name: name,
            #dayOfWeek: dayOfWeek,
            #notes: notes,
            #orderIndex: orderIndex,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteWorkout(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWorkout,
          [
            userId,
            programId,
            weekId,
            workoutId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i9.Exercise>> getExercises(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [
            userId,
            programId,
            weekId,
            workoutId,
          ],
        ),
        returnValue: _i4.Stream<List<_i9.Exercise>>.empty(),
      ) as _i4.Stream<List<_i9.Exercise>>);

  @override
  _i4.Stream<_i9.Exercise?> getExercise(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercise,
          [
            userId,
            programId,
            weekId,
            workoutId,
            exerciseId,
          ],
        ),
        returnValue: _i4.Stream<_i9.Exercise?>.empty(),
      ) as _i4.Stream<_i9.Exercise?>);

  @override
  _i4.Future<String> createExercise(_i9.Exercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [exercise],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createExercise,
            [exercise],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateExercise(_i9.Exercise? exercise) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [exercise],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateExerciseFields({
    required String? userId,
    required String? programId,
    required String? weekId,
    required String? workoutId,
    required String? exerciseId,
    String? name,
    _i9.ExerciseType? exerciseType,
    String? notes,
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExerciseFields,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekId: weekId,
            #workoutId: workoutId,
            #exerciseId: exerciseId,
            #name: name,
            #exerciseType: exerciseType,
            #notes: notes,
            #orderIndex: orderIndex,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteExercise(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            userId,
            programId,
            weekId,
            workoutId,
            exerciseId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i10.ExerciseSet>> getSets(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSets,
          [
            userId,
            programId,
            weekId,
            workoutId,
            exerciseId,
          ],
        ),
        returnValue: _i4.Stream<List<_i10.ExerciseSet>>.empty(),
      ) as _i4.Stream<List<_i10.ExerciseSet>>);

  @override
  _i4.Stream<_i10.ExerciseSet?> getSet(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
    String? setId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSet,
          [
            userId,
            programId,
            weekId,
            workoutId,
            exerciseId,
            setId,
          ],
        ),
        returnValue: _i4.Stream<_i10.ExerciseSet?>.empty(),
      ) as _i4.Stream<_i10.ExerciseSet?>);

  @override
  _i4.Future<String> createSet(_i10.ExerciseSet? set) => (super.noSuchMethod(
        Invocation.method(
          #createSet,
          [set],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createSet,
            [set],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateSet(_i10.ExerciseSet? set) => (super.noSuchMethod(
        Invocation.method(
          #updateSet,
          [set],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSet(
    String? userId,
    String? programId,
    String? weekId,
    String? workoutId,
    String? exerciseId,
    String? setId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSet,
          [
            userId,
            programId,
            weekId,
            workoutId,
            exerciseId,
            setId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> batchUpdateSets(List<_i10.ExerciseSet>? sets) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateSets,
          [sets],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reorderWeeks({
    required String? userId,
    required String? programId,
    required List<String>? weekIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderWeeks,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekIds: weekIds,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reorderWorkouts({
    required String? userId,
    required String? programId,
    required String? weekId,
    required List<String>? workoutIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderWorkouts,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekId: weekId,
            #workoutIds: workoutIds,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reorderExercises({
    required String? userId,
    required String? programId,
    required String? weekId,
    required String? workoutId,
    required List<String>? exerciseIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderExercises,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekId: weekId,
            #workoutId: workoutId,
            #exerciseIds: exerciseIds,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reorderSets({
    required String? userId,
    required String? programId,
    required String? weekId,
    required String? workoutId,
    required String? exerciseId,
    required List<String>? setIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderSets,
          [],
          {
            #userId: userId,
            #programId: programId,
            #weekId: weekId,
            #workoutId: workoutId,
            #exerciseId: exerciseId,
            #setIds: setIds,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i11.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WorkoutAnalytics> computeWorkoutAnalytics({
    required String? userId,
    required _i2.DateRange? dateRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeWorkoutAnalytics,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
          },
        ),
        returnValue:
            _i4.Future<_i2.WorkoutAnalytics>.value(_FakeWorkoutAnalytics_0(
          this,
          Invocation.method(
            #computeWorkoutAnalytics,
            [],
            {
              #userId: userId,
              #dateRange: dateRange,
            },
          ),
        )),
      ) as _i4.Future<_i2.WorkoutAnalytics>);

  @override
  _i4.Future<_i2.ActivityHeatmapData> generateHeatmapData({
    required String? userId,
    required int? year,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateHeatmapData,
          [],
          {
            #userId: userId,
            #year: year,
          },
        ),
        returnValue: _i4.Future<_i2.ActivityHeatmapData>.value(
            _FakeActivityHeatmapData_1(
          this,
          Invocation.method(
            #generateHeatmapData,
            [],
            {
              #userId: userId,
              #year: year,
            },
          ),
        )),
      ) as _i4.Future<_i2.ActivityHeatmapData>);

  @override
  _i4.Future<List<_i2.PersonalRecord>> getPersonalRecords({
    required String? userId,
    int? limit,
    _i9.ExerciseType? exerciseType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonalRecords,
          [],
          {
            #userId: userId,
            #limit: limit,
            #exerciseType: exerciseType,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.PersonalRecord>>.value(<_i2.PersonalRecord>[]),
      ) as _i4.Future<List<_i2.PersonalRecord>>);

  @override
  _i4.Future<_i2.PersonalRecord?> checkForNewPR({
    required _i10.ExerciseSet? set,
    required _i9.Exercise? exercise,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForNewPR,
          [],
          {
            #set: set,
            #exercise: exercise,
          },
        ),
        returnValue: _i4.Future<_i2.PersonalRecord?>.value(),
      ) as _i4.Future<_i2.PersonalRecord?>);

  @override
  _i4.Future<Map<String, dynamic>> computeKeyStatistics({
    required String? userId,
    required _i2.DateRange? dateRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeKeyStatistics,
          [],
          {
            #userId: userId,
            #dateRange: dateRange,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
